# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task setup-local-env
      - task build-lambdas
      - task deploy-local
    silent: true

  setup-local-env:
    dir: ./test-environment
    cmds:
      - ./setup-local-env.sh
    silent: true

  build-lambdas:
    cmds:
      - ./scripts/build_lambdas.sh &> /dev/null
    silent: true

  deploy-local:
    dir: ./infrastructure
    cmds:
      - npm run test
      - cdklocal deploy --require-approval never
    silent: true
