AWSTemplateFormatVersion: 2010-09-09

Resources:
  MyTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      TopicName: 'MyTopic'

  MyQueue1:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'MyQueue1'
  MyQueue2:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: 'MyQueue2'

  Queue1Subscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref MyTopic
      Endpoint: !GetAtt
        - MyQueue1
        - Arn
      Protocol: sqs
      RawMessageDelivery: 'true'
  Queue2Subscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      TopicArn: !Ref MyTopic
      Endpoint: !GetAtt
        - MyQueue2
        - Arn
      Protocol: sqs
      RawMessageDelivery: 'true'


  MyQueuePolicy:
    Type: 'AWS::SQS::QueuePolicy'
    Properties:
      PolicyDocument:
        Id: MyQueuePolicy
        Statement:
          - Sid: Allow-SendMessage-To-Both-Queues-From-SNS-Topic
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - 'sqs:SendMessage'
            Resource: '*'
            Condition:
              ArnEquals:
                'aws:SourceArn': !Ref MyTopic
      Queues:
        - !Ref MyQueue1
        - !Ref MyQueue2