version: "3.3"

networks:
  test-network:

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory" ]
    networks:
      - test-network

  localstack:
    image: 'localstack/localstack:0.12.5'
    restart: always
    ports:
      - 4566:4566
    environment:
      - DEFAULT_REGION=eu-west-1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - test-network
