version: '3'

tasks:
  default:
    deps: [ check-preconditions ]
    desc: deploy to aws
    cmds:
      - task build
      - task deploy

  check-preconditions:
    desc: check if all tools for development are installed and running
    cmds:
      - tsc -version &> /dev/null
      - cdk --version &> /dev/null
    silent: true

  build:
    desc: build all lambdas from folder functions
    cmds:
      - task build-file-import-lambda

  build-file-import-lambda:
    desc: build file import lambda
    dir: functions/file_import
    cmds:
      - tsc

  deploy:
    desc: deploy lambdas to aws
    dir: environment
    cmds:
      - cdk deploy

  destroy:
    desc: destroy cdk stack
    dir: environment
    cmds:
      - cdk destroy